#!/usr/bin/env node
const repoOwner = require('git-remote-origin-url').getUrl().replace(/:/g, '/').split('/')[1];
const repoName = require('git-repo-name');

require('dotenv').config();
const secrets = Object.entries(process.env);

const { Secrets } = require('gh-cli');
const { set } = new Secrets(repoOwner, repoName);
secrets.forEach(([key, value]) => set(key, value));
