#!/usr/bin/env node
const gitRemoteOriginUrl = require('git-remote-origin-url');
const gitRepoName = require('git-repo-name');
const dotenv = require('dotenv');
const { Secrets } = require('gh-cli');

dotenv.config();

const repoOwner = gitRemoteOriginUrl.getUrl().replace(/:/g, '/').split('/')[1];
const repoName = gitRepoName();
const secrets = Object.entries(process.env);

const { set } = new Secrets(repoOwner, repoName);
secrets.forEach(([key, value]) => set(key, value));
